# Generated by Django 4.2.13 on 2024-08-27 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0004_video_category'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='viseos',
            field=models.ManyToManyField(blank=True, to='video.video'),
        ),
    ]
