# Generated by Django 4.2.13 on 2024-08-27 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_viseos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='viseos',
            new_name='videos',
        ),
    ]
